export const FETCHING_STOPS_INITIATED = 'FETCHING_STOPS_INITIATED';
export const FETCHING_STOPS_FINISHED = 'FETCHING_STOPS_FINISHED';
export const FETCHING_STOPS_RECEIVED = 'FETCHING_STOPS_RECEIVED';

export const FETCHING_DEPARTURES_INITIATED = 'FETCHING_DEPARTURES_INITIATED';
export const FETCHING_DEPARTURES_FINISHED = 'FETCHING_DEPARTURES_FINISHED';
export const FETCHING_DEPARTURES_FAILED = 'FETCHING_DEPARTURES_FAILED';

export const FETCHING_LOCATIONS_INITIATED = 'FETCHING_DEPARTURES_INITIATED';
export const FETCHING_LOCATIONS_FINISHED = 'FETCHING_DEPARTURES_FINISHED';
export const FETCHING_LOCATIONS_FAILED = 'FETCHING_DEPARTURES_FAILED';
